### ISSUE TITLE
Any particular reason for using Python 2? 

### ISSUE THREAD

**Issue by imsrgadich** [zbchern/Neural-Relational-Topic-Models#1]
Looking forward to the answer. 

best regards,
Srikanth

**Comment by zbchern** [comment]
Hi Srikanth, thanks for your question and sorry for the late reply.

No, indeed no particular reason for using Python 2. Actually I just try Python 3, and the code works fine without any modification : )

**Comment by imsrgadich** [comment]
@zbchern Thank you for the reply. Great to know it works for Python 3. :)
